### PR TITLE
Add tooling to pack and test all project templates

### PR DESCRIPTION
**Pull request by kMutagene**
This pr adds improved tooling for developing the fsr templates such as a pack and test script.

### CODE REVIEW

**Comment by HLWeil** [comment]
Hey, 

great changes for a more controlled and streamlined development workflow. But when testing the `testTemplate` target I got the following error: 

`One or more errors occurred. (Start of process 'dotnet.exe' failed. WorkingDir 'C:\Users\HLWei\Downloads\FSharpReady-MetaTooling\tests/slim' does not exist.)`

Creating the `tests/slim` folder myself before building solves the problem. Do you have an idea what the cause might be?

**Comment by HLWeil** [comment]
Also it would be great if you could update the `README` to include the new template.

**Comment by kMutagene** [comment]
Yeah seems like you cant track empty folders in git. Fixed it by creating those folders in the test targets. The new project is not contained in this pr, it will come in separate to keep commit history clean (i removed leftover references in this PR)

**Review by HLWeil — COMMENTED** [review]
Couldn't we remove the csproj file now?

**Comment by kMutagene** [comment]
No. it contains the meta information on what and how to pack. you can rename it to be a .fsproj file, or even a .proj file though, that does not matter.

**Comment by HLWeil** [comment]
Whoops yeah nvm. I'll merge now

**Pull request merged**
